apiVersion: v1
kind: Service

metadata:
  name: apache-service
  namespace: apache

spec:
  selector:
    app: apache

  ports:
    - protocol: TCP
      # exposed port in the cluster
      port: 80
      # container port
      targetPort: 80

  type: ClusterIP
